Error occurred during training. Error: __init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/Users/ammar/Ready Tensor/src/train.py", line 95, in run_training
    data_balancer_pipeline = Pipeline([('DataBalancer',DataBalancer(data_schema.target))])
TypeError: __init__() takes 1 positional argument but 2 were given
